version: '3.4'

services:
  productsmongodb:
    image: mongo

  products.api:
    image: vishipayyallore/eshop-services-products
    build:
      context: .
      dockerfile: Source/Products.API/Dockerfile

  configuration.api:
    image: vishipayyallore/eshop-services-configuration

volumes:
  mongo_data:
