version: '3.4'

services:
  productsmongodb:
    container_name: eshop-store-products
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  products.api:
    container_name: eshop-services-products
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - "MongoDbSettings__ConnectionString=mongodb://eshop-store-products:27017"
    depends_on:
      - productsmongodb
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro