name: "03. Build and Push Docker Image"

on:
  workflow_call:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  WORKING_DIRECTORY: "./Source/Products.API"

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.0.1
        with:
          # List of Docker images to use as base name for tags
          images: vishipayyallore/eshop-services-products
          # GitHub Token as provided by secrets
          github-token: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          # context: ./Source/Products.API
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
