name: "A3 Build and Push Docker Image"

on:
  workflow_call:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  WORKING_DIRECTORY: "./Source/Products.API"

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.0.1
        with:
          images: vishipayyallore/eshop-services-products
          github-token: ${{ github.token }}

      - name: Tags
        run: echo Tags ${{ steps.meta.outputs.tags }}

      - name: Set start timestamp
        id: start
        run: |
          printf '::set-output name=timestamp::%(%s)T\n'

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ${{ env.WORKING_DIRECTORY }}/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/eshop-services-products:latest,${{ env.DOCKER_USERNAME }}/eshop-services-products:${{ steps.start.outputs.timestamp }}
          labels: ${{ steps.meta.outputs.labels }}
