name: "A4 Deploy Docker Image to AKS"

on:
  workflow_call:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  CLUSTER_NAME: "rg-eshop-dev-001-cluster"
  RESOURCE_GROUP: "rg-eshop-dev-001"

jobs:
  deploy-docker-image-to-aks:
    runs-on: ubuntu-latest
    environment: Development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.5
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      # Deploys application based on manifest files from previous step
      - name: Deploy Products API to AKS
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: |
            https://raw.githubusercontent.com/vishipayyallore/eshop-services-products/main/Deploy/eshop-products-api-k8s.yml
          images: |
            ${{ env.DOCKER_USERNAME }}/eshop-services-products:latest

# Deploy/eshop-products-api-k8s.yml