name: "A4 Deploy Docker Image to AKS"

on:
  workflow_call:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  CLUSTER_NAME: k8s-eshop
  RESOURSE_GROUP: rg-womd-dev-001

jobs:
  # permissions:
  #   actions: read
  #   contents: read
  #   id-token: write
  build-push-docker-image:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.5
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      # Deploys application based on manifest files from previous step
      - name: Deploy Products API to AKS
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: |
            Deploy/eshop-products-api-k8s.yml
          images: |
            ${{ secrets.DOCKER_USERNAME }}/eshop-services-products:latest
