# To Build, Publish, and Push to Docker Hub Products-API

name: A5 Main Products Api CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gated-build-services-products:
    name: Gated Build Services Products When PR is Raised
    uses: ./.github/workflows/A1-Gated-Build-Services-Products.yml
    secrets: inherit

  ci-build-services-products:
    name: CI Build Services Products When PR is Approved
    if: ${{ github.ref_name == 'main' }}
    needs: [gated-build-services-products]
    uses: ./.github/workflows/A2-CI-Build-Services-Products.yml
    secrets: inherit

  build-push-docker-image:
    name: Build and Push Docker Image When PR is Approved
    if: ${{ github.ref_name == 'main' }}
    needs: [ci-build-services-products]
    uses: ./.github/workflows/A3-Build-Push-DockerImage.yml
    secrets: inherit

  deploy-docker-image-to-aks:
    # name: Deploy Docker Image to AKS When Release is Approved
    # if: ${{ github.ref_name == 'main' }}
    needs: [gated-build-services-products]
    uses: ./.github/workflows/A4-Deploy-DockerImage-ToAKS.yml
    secrets: inherit
